version: 2
jobs:
  unit-test:
    parallelism: 1
    working_directory: ~/nomad-migrators-datomic
    docker:
      - image: omnyway/vulcan:latest
      - image: postgres:9.6.2
    environment:
      - SERVICE_NAME: nomad-migrators-datomic
    steps:
      - checkout
  release:
    parallelism: 1
    working_directory: ~/nomad-migrators-datomic
    docker:
      - image: omnyway/vulcan:latest
    environment:
      - VERSION_FILE: ../VERSION
      - SERVICE_NAME: nomad-migrators-datomic
      - GOROOT: ""
      - GOPATH: "/root/.go"
    steps:
      - checkout
      - run: vulcan next-tag > $VERSION_FILE
      - run: export SEMVER=$(cat $VERSION_FILE); github-release release --user omnyway-labs --repo nomad --tag $SEMVER  --target $CIRCLE_SHA1
workflows:
  version: 2
  build_test_release:
    jobs:
      - unit-test
      - release:
          requires:
            - unit-test
          filters:
            branches:
              only: master
